import { Event } from '@/types';

export function formatTime(timeStr?: string): string {
  if (!timeStr) return '';
  const trimmed = timeStr.trim();
  if (!trimmed) return '';
  if (/am|pm/i.test(trimmed)) return trimmed;
  const parts = trimmed.split(':');
  let h = parseInt(parts[0], 10);
  if (isNaN(h)) return trimmed;
  const m = parts[1] ? parts[1].padStart(2, '0') : '00';
  const ampm = h >= 12 ? 'PM' : 'AM';
  h = h % 12;
  if (h === 0) h = 12;
  const formattedH = h.toString().padStart(2, '0');
  return `${formattedH}:${m} ${ampm}`;
}

export function formatTimeRange(start?: string, end?: string): string {
  if (!start) return '';
  const formattedStart = formatTime(start);
  if (!end) return formattedStart;
  const formattedEnd = formatTime(end);
  return `${formattedStart} – ${formattedEnd}`;
}

export const OFFICIAL_EVENTS: Event[] = [
  // ── 1. TECHNICAL EVENTS ──
  {
    id: 'tech-1',
    slug: 'tech-talks',
    name: 'Tech Talks',
    category: 'technical',
    description: 'Present your innovative ideas and research papers to a panel of industry experts on cutting-edge IT topics.',
    rules: [
      'Maximum of 2 members | ₹100 per head',
      'Each team should submit a soft copy of the paper before presentation.',
      'Each team has 5 minutes to present their topic, followed by 2 minutes of questionnaires.',
      'Topics: Quantum Computing, Generative AI, Cybersecurity, or any topic related to IT domain.'
    ],
    venue: 'IT Smart Room',
    date: '2026-08-22',
    startTime: '11:00',
    endTime: '13:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 100,
    maxParticipants: 2,
    registeredCount: 0,
    coordinatorName: 'Mohammed Dhaniyal & Masood Nawaz',
    organizerName: 'Department of Information Technology',
    contactNumber: '7010155779, 9944410994',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tech-2',
    slug: 'codestorm',
    name: 'Codestorm (Coding & Debugging)',
    category: 'technical',
    description: 'Two-round coding & debugging challenge testing speed, accuracy, and problem-solving skills across any programming language.',
    rules: [
      'Maximum of 2 members | ₹50 per head',
      'First round has 20 questions in 30 minutes.',
      'Second round: Coding & Debugging. Participants should solve 5 questions in 1 hour using any language.',
      'Computers will be provided.'
    ],
    venue: 'Lab 5 (Tech Tower)',
    date: '2026-08-22',
    startTime: '11:00',
    endTime: '13:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 2,
    registeredCount: 0,
    coordinatorName: 'Mohammed Irfan & Thoufeeq Ahmed',
    organizerName: 'Department of Information Technology',
    contactNumber: '9042469482, 9150654995',
    bannerUrl: '/events/codestorm.jpeg',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tech-3',
    slug: 'pixel-craft',
    name: 'Pixel Craft',
    category: 'technical',
    description: 'Design and develop responsive web interfaces and UI/UX designs on an on-the-spot topic.',
    rules: [
      'Maximum of 2 members | ₹100 per head',
      'No templates will be provided and participants should bring their laptop.',
      'Topic will be given on the spot.'
    ],
    venue: 'IT Final Year Classroom',
    date: '2026-08-22',
    startTime: '11:00',
    endTime: '13:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 100,
    maxParticipants: 2,
    registeredCount: 0,
    coordinatorName: 'Mathin S & Manikandan T',
    organizerName: 'Department of Information Technology',
    contactNumber: '6381880659, 8825940089',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tech-4',
    slug: 'open-source',
    name: 'Open Source',
    category: 'technical',
    description: 'Single-round open-source workflow challenge: Find, fix, and improve a given codebase using Git and GitHub.',
    rules: [
      'Maximum of 2 members | ₹100 per head',
      'One round: Find, Fix & Improve a given codebase.',
      'Fork → Code → Commit → Push → Pull Request → Complete the open-source workflow.',
      'Bring your laptop.',
      'A laptop with Git/GitHub access and required coding tools is mandatory/recommended for participation.'
    ],
    venue: 'Lab 6 (Tech Tower)',
    date: '2026-08-22',
    startTime: '12:00',
    endTime: '14:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 100,
    maxParticipants: 2,
    registeredCount: 0,
    coordinatorName: 'Saheem & Zahid',
    organizerName: 'Department of Information Technology',
    contactNumber: '9489016294, 7639412328',
    bannerUrl: '/events/open-source.jpeg',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tech-5',
    slug: 'byte-battle',
    name: 'Byte Battle',
    category: 'technical',
    description: 'Fast-paced technical contest testing your knowledge of IT domain concepts.',
    rules: [
      'Maximum of 2 members | ₹50 per head',
      'Participants should bring a mobile phone.',
      'Gadgets, AI are not allowed.'
    ],
    venue: 'AIDS & CSM, III-A Class',
    date: '2026-08-22',
    startTime: '11:00',
    endTime: '13:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 2,
    registeredCount: 0,
    coordinatorName: 'Ezthilarasan & Dinesh Babu',
    organizerName: 'Department of Information Technology',
    contactNumber: '9080249831, 6374468780',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tech-6',
    slug: 'hack-forge',
    name: 'Hack Forge (Mini Hackathon)',
    category: 'technical',
    description: 'Open innovation mini hackathon & project pitching contest featuring a 5-minute prototype pitch and 1-minute final pitch.',
    rules: [
      'Maximum of 2 members (Individual / 2 members) | ₹100 per head',
      'Round 1: 5-minute prototype pitch.',
      'Round 2: 1-minute final pitch.'
    ],
    venue: 'AIDS Smart Room',
    date: '2026-08-22',
    startTime: '12:00',
    endTime: '14:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 100,
    maxParticipants: 2,
    registeredCount: 0,
    coordinatorName: 'Kashif',
    organizerName: 'Department of Information Technology',
    contactNumber: '6380028607',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tech-7',
    slug: 'clash-of-minds',
    name: 'Clash of Minds',
    category: 'technical',
    description: 'Technical debate contest where one team member speaks for the topic and the other speaks against it.',
    rules: [
      'Team of 2 | ₹50 per head',
      'One participant speaks for the topic and the other against the topic.',
      'Topics will be given on the spot.',
      'Each team gets 6 minutes to present.'
    ],
    venue: 'ECE Classroom',
    date: '2026-08-22',
    startTime: '11:30',
    endTime: '12:30',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 2,
    registeredCount: 0,
    coordinatorName: 'Amirtha Varshini & Keerthana',
    organizerName: 'Department of Information Technology',
    contactNumber: '9597010159, 9629909942',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── 2. NON-TECHNICAL EVENTS ──
  {
    id: 'nontech-1',
    slug: 'mind-matrix',
    name: 'Mind Matrix (Connections)',
    category: 'non-technical',
    description: 'Connect displayed images on screen to solve non-technical trivia, connections, and mind-bending puzzles.',
    rules: [
      'Maximum of 2 members | ₹50 per head',
      'Connect the images displayed on the screen and find the answer.',
      'Non-technical-based questions/hints.'
    ],
    venue: '3rd IT A & B Classrooms',
    date: '2026-08-22',
    startTime: '14:00',
    endTime: '15:30',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 2,
    registeredCount: 0,
    coordinatorName: 'Naushin & Hema Malini',
    organizerName: 'Department of Information Technology',
    contactNumber: '7358170392, 7418575021',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nontech-2',
    slug: 'quest-x',
    name: 'Quest X (Treasure Hunt)',
    category: 'non-technical',
    description: 'Campus-wide treasure hunt. Follow sequential clues as a team to find the hidden treasure.',
    rules: [
      'Maximum of 4 members | ₹50 per head',
      'Follow the clues in order. No skipping.',
      'Stay together as a team.',
      'First team to find the treasure wins.'
    ],
    venue: 'EEE Classroom',
    date: '2026-08-22',
    startTime: '13:30',
    endTime: '15:30',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 4,
    registeredCount: 0,
    coordinatorName: 'Shyam Sundar & Maithreyan',
    organizerName: 'Department of Information Technology',
    contactNumber: '9345837870, 9342706675',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nontech-3',
    slug: 'frame-craft',
    name: 'Frame Craft (Photography)',
    category: 'non-technical',
    description: 'On-spot mobile photography contest capturing campus moments matching the given theme.',
    rules: [
      'Maximum of 1 member | ₹50 per head',
      'On-spot topic will be provided.',
      'Only mobile photos will be accepted.',
      'Photos should be taken inside the college campus and should match the theme.'
    ],
    venue: '2nd Year IT Class',
    date: '2026-08-22',
    startTime: '14:00',
    endTime: '16:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 1,
    registeredCount: 0,
    coordinatorName: 'Jeysha & Siddharth',
    organizerName: 'Department of Information Technology',
    contactNumber: '9345110882, 8925444109',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nontech-4',
    slug: 'fun-fiesta',
    name: 'Fun Fiesta',
    category: 'non-technical',
    description: 'High-energy mini-games and spot challenges with exciting prizes throughout the day.',
    rules: [
      'Maximum of 4 members | ₹50 per head',
      'Spot entry mini-games and challenges throughout the day.'
    ],
    venue: 'Main Lawn',
    date: '2026-08-22',
    startTime: '09:30',
    endTime: '16:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 4,
    registeredCount: 0,
    coordinatorName: 'Jaffreen & Talha',
    organizerName: 'Department of Information Technology',
    contactNumber: '9344814392, 8610117244',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nontech-5',
    slug: 'artistry',
    name: 'Artistry',
    category: 'non-technical',
    description: 'Fine art, mehendi, and creative illustration contest testing artistic skills and imagination.',
    rules: [
      'Maximum of 1 member | ₹50 per head',
      'Required things should be brought by participants.',
      'No reference materials or phones are allowed.'
    ],
    venue: 'EEE Classroom',
    date: '2026-08-22',
    startTime: '14:00',
    endTime: '15:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 1,
    registeredCount: 0,
    coordinatorName: 'Haniya Nikhat & Harshitha',
    organizerName: 'Department of Information Technology',
    contactNumber: '8248478615, 9629136470',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nontech-6',
    slug: 'flavour-fusion',
    name: 'Flavour Fusion (Fireless Fiesta)',
    category: 'non-technical',
    description: 'No-fire cooking & culinary contest evaluated on food taste, presentation, area cleanliness, and number of dishes.',
    rules: [
      'Maximum of 4 members | ₹50 per head',
      'Pre-cooked food is not allowed. Required things should be brought by yourself.',
      'Winner will be decided based on: Food taste, Presentation, Cleanliness of the place, and Number of dishes.'
    ],
    venue: 'Physics Lab',
    date: '2026-08-22',
    startTime: '11:30',
    endTime: '12:30',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 4,
    registeredCount: 0,
    coordinatorName: 'Jeevitha & Poorna Sree',
    organizerName: 'Department of Information Technology',
    contactNumber: '9384505002, 9600889789',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nontech-7',
    slug: 'battle-verse',
    name: 'Battle Verse',
    category: 'non-technical',
    description: 'BGMI & Free Fire Battle Royale gaming tournament with strict fair-play guidelines (Solo or Team up to 4).',
    rules: [
      'Maximum of 4 members | Team registration: ₹60 | Solo registration: ₹50 per person',
      'Using emotes is strictly prohibited. If used, the participant/team will be disqualified.',
      'Only BR (Battle Royale) matches are allowed.',
      'People who cause skirmish or quarrel will be eliminated immediately.',
      'Gun skins are allowed, but character skill is prohibited.',
      'Winners (1st and 2nd) will be selected based on Booyah, Chicken Dinner, and Runner Up standings.'
    ],
    venue: 'Auditorium',
    date: '2026-08-22',
    startTime: '14:00',
    endTime: '15:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 60,
    maxParticipants: 4,
    registeredCount: 0,
    coordinatorName: 'Meshak & Sanjay V',
    organizerName: 'Department of Information Technology',
    contactNumber: '6383598812, 6382143386',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nontech-8',
    slug: 'mic-drop',
    name: 'Mic Drop (Open Mic)',
    category: 'non-technical',
    description: 'Open mic stage for solo singing, poetry, stand-up comedy, and acoustic performances.',
    rules: [
      'Registration: ₹50 per head',
      'Only singing, poetry, comedy, etc. will be allowed.',
      'Dance or heavy acts are not allowed for this event.'
    ],
    venue: 'ECE Room',
    date: '2026-08-22',
    startTime: '14:00',
    endTime: '15:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 1,
    registeredCount: 0,
    coordinatorName: 'Garnet & Heena',
    organizerName: 'Department of Information Technology',
    contactNumber: '6374139336, 8072672922',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nontech-9',
    slug: 'reel-it-feel-it',
    name: 'Reel It Feel It',
    category: 'non-technical',
    description: 'Short mobile reel/video contest on an on-the-spot topic filmed inside campus.',
    rules: [
      'Maximum of 2 members | ₹50 per head',
      'An on-spot topic will be provided. Maximum 2 members are allowed.',
      'Only mobiles will be allowed to take videos.',
      'Videos should be taken inside the college campus and should match the topic.'
    ],
    venue: '2nd Year IT-A (CSE)',
    date: '2026-08-22',
    startTime: '14:00',
    endTime: '15:00',
    registrationDeadline: '2026-08-20',
    registrationFee: 50,
    maxParticipants: 2,
    registeredCount: 0,
    coordinatorName: 'Naveeth Khan & Faizal Ahmed',
    organizerName: 'Department of Information Technology',
    contactNumber: '9360257573, 9003710032',
    status: 'upcoming',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
